config/routes.rb
Rails.application.routes.draw do
  
  get 'attendances/create'
  get 'attendances/new'
  get 'invitations/create'
  get 'invitations/destroy'
  get 'invitations/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/signout',  to: 'sessions#destroy'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'

  resources :users
  get 'event/attend', to: 'events#attend'
  resources :events
  
  get 'new/create'
  get 'new/show'
  root 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/attended_event.rb
class AttendedEvent < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord

    scope :upcoming, -> { where("event_date >= ?", Date.today) }
    scope :past, -> { where("event_date < ?", Date.today) }


    belongs_to :creator, class_name: "User"
    has_many :attendances, foreign_key: "attended_event_id"
    has_many :attendees, through: :attendances
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :events
end

app/models/user.rb
class User < ApplicationRecord

    has_many :events, foreign_key: "creator_id", class_name: "Event"
    has_many :attendances, foreign_key: "attendee_id"
    has_many :attended_events, through: :attendances


    def upcoming_events_to_attend
        self.attended_events.where("event_date > ?", Date.today)
    end
    
    def previous_attended_events
        self.attended_events.where("event_date < ?", Date.today)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    # helper_method :current_user

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def create
      @event = Event.find(params[:format])
      current_user.event_attendance << @event
      redirect_to @event
  end

  def new
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include SessionsHelper
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:create, :new, :show]

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = "Event Created Successfully"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def index
    @events = Event.all
    @past = Event.past
    @future = Event.upcoming
  end

  def show
    #@event = Event.find(params[:id])
  end

  private

    def set_event
      @event = Event.find(params[:id])
      event = @event
    end

    def event_params
      params.require(:event).permit(:name, :description, :event_date)
    end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def create
  end

  def destroy
  end

  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if params[:user]
      user = User.find_by_email(params[:user][:email])
      if user
        log_in(user)
      else
        flash.now[:danger] = 'Invalid email'
        render 'New'
      end
    end
  end

  def destroy
    log_out if logged_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find_by(id: params[:id])
      
    @upcoming_events = current_user.upcoming_events_to_attend
    @previous_events = current_user.previous_attended_events
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:info] = "Account Created Successfully"
      log_in(@user)
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
    def can_attend?(event)
        return current_user.attended_events.exists?(event.id) || event.event_date < Date.today
    end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
        redirect_to user
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
        redirect_to root_url
    end    

    def current_user
        if session[:user_id]
          @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    def logged_in?
        !current_user.nil?
    end

    
    def logged_in_user
        unless logged_in?
          flash[:danger] = "Please log in."
          redirect_to login_url
        end
      end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/create.html.erb
<h1>Attendances#create</h1>
<p>Find me in app/views/attendances/create.html.erb</p>

app/views/attendances/new.html.erb
<h1>Attendances#new</h1>
<p>Find me in app/views/attendances/new.html.erb</p>

app/views/events/_event.html.erb
<tr>
<td><%= event.name %></td>
<td><%= event.description %></td>
<td><%= link_to event.creator.name, event.creator %></td>
<td><%= link_to 'Show', event %></td>
</tr>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<div class="container">
    <h2>All Events</h2>

    <div class="d-flex justify-content-end mb-3">
      <button type="button" class="btn btn-primary"><%= link_to 'Create Event', new_event_path, class: 'white' %></button>
    </div>


    <div class="card">

      <div class="card-title">
        <h3 class="pl-4 pt-4">Upcoming Events</h3>
      </div>

<div class="card-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Creator</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: "event", collection: @future %>
        </tbody>
      </table>
      </div>
    </div>





    <div class="card mt-4">

    <div class="card-title">
        <h3 class="pl-4 pt-4">Past Events</h3>
      </div>

      <div class="card-body">

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Creator</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
            
              <%= render partial: "event", collection: @past %>
            
        
        </tbody>
      </table>
      </div>
    </div>

    


    

  </div>

app/views/events/new.html.erb
<div class="container">

<h2>New Event</h2>

<%= form_for(@event) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :description %>
  <%= f.text_area :description, placeholder: "Enter Description...", class: 'form-control' %>

  <%= f.label :event_date, 'Date of Event' %>
  <%= f.date_field :event_date, class: 'form-control' %>
  
  <%= f.submit "Create Event", class: "btn btn-primary mt-2" %>
  <div class="d-flex justify-content-end mt-3">
      <button type="button" class="btn btn-default"><%= link_to 'Go Back', :back, class: 'white' %></button>
    </div>
<% end %>



    </div>

app/views/events/show.html.erb
<div class="container">
    <% if @event.event_date < Date.today %>
        <p class="alert">Event already took place</p>
    <% end %>

    <h5>Event Details</h5>
    <h2>Name: <%= @event.name %></h2>
    <p>Description: <%= @event.description %></p>
    <p>Date: <%= @event.event_date %></p>

    <p class="m-b-2">created by: <%= @event.creator.name %></p>



    <div class="row">
        <div class="col-md-6">
            <h4>Event Attendees</h4>
            <% if @event.attendees.any? %>
                <ul class="list-group list-group-flush">
                    <% @event.attendees.each do |attendee| %>
                        <li class="list-group-item"><%= attendee.name %> <li>
                    <% end %>
                </ul>
            <% else %>
                <div class="alert alert-info">No event attendees yet</div>
            <% end %>
        </div>
    </div>


    <div class="d-flex justify-content-end mt-3">
      <%  unless can_attend?(@event) %><button type="button" class="btn btn-primary mx-2">
        <%= link_to 'Attend Event', attendances_create_path(@event), class: 'white' %></button><% end %>
      <button type="button" class="btn btn-default"><%= link_to 'Go Back', events_path, class: 'white' %></button>
    </div>
</div>

app/views/invitations/create.html.erb
<h1>Invitations#create</h1>
<p>Find me in app/views/invitations/create.html.erb</p>

app/views/invitations/destroy.html.erb
<h1>Invitations#destroy</h1>
<p>Find me in app/views/invitations/destroy.html.erb</p>

app/views/invitations/new.html.erb
<h1>Invitations#new</h1>
<p>Find me in app/views/invitations/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <nav class="navbar navbar-light bg-light justify-content-between">
        <%= link_to "Private Events", root_path, class: 'justify-content-start navbar-brand' %>
        
        <% if current_user  %>
        <ul class="list-inline-mb-0">
          <li class="list-inline-item"><%= link_to "All Events", events_path %></li>
          <li class="list-inline-item"><button class="btn btn-info"><%= link_to "Log out", signout_path, method: :delete, class: "white" %></button></li>
        </ul>

        <% else %>
          <ul>
            <% unless current_page?('/login') %>
              <li class="list-inline-item"><button class="btn btn-info"><%= link_to "Log in", login_path, class: 'white' %></button></li>
            <% end %>
            
            <li class="list-inline-item"><button class="btn btn-info"><%= link_to "Sign Up", signup_path, class: 'white' %></button></li>
          </ul>
        <% end %>
      </nav>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:user, url: signup_path) do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.submit "Sign Up", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row m-y-2">
      <div class="col-lg-4 pull-lg-8 text-xs-center">
          <h3 class="m-t-2"><%= @user.name %></h3>
          <p>User ID: <%= @user.id %> (Used for Logging In)<p>

          <div class="d-flex justify-content-start mb-3">
            <button type="button" class="btn btn-primary"><%= link_to 'Create Event', new_event_path, class: 'white' %></button>
          </div>
      </div>

      <div class="col-lg-8 push-lg-4">
          <ul class="nav nav-tabs">
              <li class="nav-item">
                  <a href="" data-target="#profile" data-toggle="tab" class="nav-link active">Created Events (<%= @user.events.count %>)</a>
              </li>
              <li class="nav-item">
                  <a href="" data-target="#messages" data-toggle="tab" class="nav-link">Attending (<%= @upcoming_events.count %>)</a>
              </li>
              <li class="nav-item">
                  <a href="" data-target="#edit" data-toggle="tab" class="nav-link">Attended (<%= @previous_events.count %>)</a>
              </li>
          </ul>
          <div class="tab-content p-b-3">
              <div class="tab-pane active" id="profile">
                  <div class="row">
                      <div class="col-md-6">
                        <% if @user.events.any? %>
                          <ul class="list-group list-group-flush">
                            <% @user.events.each do |event| %>
                              <li class="list-group-item"><%= event.name %> : <%= event.description %><li>
                            <% end %>
                          </ul>
                        <% else %>
                          <div class="alert alert-info">No event created yet</div>
                        <% end %>
                      </div>
                  </div>
                  <!--/row-->
              </div>

              <div class="tab-pane" id="messages">
                  <h4 class="m-y-2">Future Events</h4>
                  <div class="row">
                      <div class="col-md-6">
                        <% if @upcoming_events.any? %>
                          <ul class="list-group list-group-flush">
                            <% @upcoming_events.each do |event| %>
                              <li class="list-group-item"><%= event.name %> : <%= event.description %><li>
                            <% end %>
                          </ul>
                        <% else %>
                          <div class="alert alert-info">No event</div>
                        <% end %>
                      </div>
                  </div>
              </div>

              <div class="tab-pane" id="edit">
                  <h4 class="m-y-2">Past Events</h4>
                  <div class="row">
                      <div class="col-md-6">
                        <% if @previous_events.any? %>
                          <ul class="list-group list-group-flush">
                            <% @previous_events.each do |event| %>
                              <li class="list-group-item"><%= event.name %> : <%= event.event_date %><li>
                            <% end %>
                          </ul>
                        <% else %>
                          <div class="alert alert-info">No event attended yet</div>
                        <% end %>
                      </div>
                  </div>
              </div>
          </div>
      </div>
        
    </div>
</div>
<hr>

app/views/users/signin.html.erb
<h1>Sign In</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:user, url: login_path) do |f| %>

        <%= f.label :id, 'User ID' %>
        <%= f.text_field :id, class: 'form-control' %>

        <br>

        <%= f.submit "Sign In", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>